#
# Usage:
#   conda env create --file=environment.yml -n smartjit

name: smartjit
channels:
  - conda-forge
  - numba
  - defaults
dependencies:
  - python>=3.7
  - numba>=0.55
  - llvmlite
  - pytest
